### PR TITLE
The great Parser overhaul

### PR DESCRIPTION
**Pull request by MightyCupcakes**
As stated in #31

### CODE REVIEW

**Comment by MightyCupcakes** [comment]
@tanboonjoon what do you think of this?

**Comment by tanboonjoon** [comment]
@MightyCupcakes changed tag from e/ to t/

**Comment by MightyCupcakes** [comment]
Should be fine. Ready for merging

**Comment by tanboonjoon** [comment]
@MightyCupcakes try to avoid multiple nested ifelse. avoid else if 'if' can be used explicitly 

resolve #31

**Pull request merged**
